export const data = [
  {
    id: 1,
    first_name: 'Ximenez',
    last_name: 'Middleditch',
    email: 'xmiddleditch0@godaddy.com',
    gender: 'M',
    language: 'Tamil',
    birthday: '2006-08-06',
    cycle: 'night',
  },
  {
    id: 2,
    first_name: 'Buddie',
    last_name: 'Vallery',
    email: 'bvallery1@1und1.de',
    gender: 'M',
    language: 'Hindi',
    birthday: '1997-06-25',
    cycle: 'night',
  },

  {
    id: 3,
    first_name: 'Andriette',
    last_name: 'Fryman',
    email: 'afryman2@elegantthemes.com',
    gender: 'F',
    language: 'Maltese',
    birthday: '2007-02-19',
    cycle: 'night',
  },

  {
    id: 4,
    first_name: 'Burtie',
    last_name: 'Ludwig',
    email: 'bludwig3@opera.com',
    gender: 'M',
    language: 'Icelandic',
    birthday: '1992-03-18',
    cycle: 'morning',
  },

  {
    id: 5,
    first_name: 'Regine',
    last_name: 'Varden',
    email: 'rvarden4@spiegel.de',
    gender: 'F',
    language: 'Malay',
    birthday: '1964-02-11',
    cycle: 'night',
  },

  {
    id: 6,
    first_name: 'Aubine',
    last_name: 'Casillis',
    email: 'acasillis5@scribd.com',
    gender: 'F',
    language: 'Kazakh',
    birthday: '1961-10-13',
    cycle: 'morning',
  },

  {
    id: 7,
    first_name: 'Candra',
    last_name: 'Shepherd',
    email: 'cshepherd6@ibm.com',
    gender: 'F',
    language: 'Greek',
    birthday: '1969-06-01',
    cycle: 'morning',
  },

  {
    id: 8,
    first_name: 'Lydie',
    last_name: 'De la Harpe',
    email: 'ldelaharpe7@sciencedirect.com',
    gender: 'F',
    language: 'Lithuanian',
    birthday: '1965-07-06',
    cycle: 'morning',
  },

  {
    id: 9,
    first_name: 'Henryetta',
    last_name: 'Lehr',
    email: 'hlehr8@ezinearticles.com',
    gender: 'F',
    language: 'Sotho',
    birthday: '1986-09-10',
    cycle: 'night',
  },

  {
    id: 10,
    first_name: 'Tiffie',
    last_name: 'Denham',
    email: 'tdenham9@imageshack.us',
    gender: 'F',
    language: 'English',
    birthday: '1984-12-28',
    cycle: 'night',
  },

  {
    id: 11,
    first_name: 'Pasquale',
    last_name: 'Goodsall',
    email: 'pgoodsalla@nature.com',
    gender: 'M',
    language: 'French',
    birthday: '1973-04-24',
    cycle: 'morning',
  },

  {
    id: 12,
    first_name: 'Klaus',
    last_name: 'Scherer',
    email: 'kschererb@census.gov',
    gender: 'M',
    language: 'Tajik',
    birthday: '1996-06-24',
    cycle: 'night',
  },

  {
    id: 13,
    first_name: 'Marion',
    last_name: 'Peare',
    email: 'mpearec@issuu.com',
    gender: 'F',
    language: 'Tsonga',
    birthday: '1952-02-05',
    cycle: 'morning',
  },

  {
    id: 14,
    first_name: 'Eustace',
    last_name: 'Prestland',
    email: 'eprestlandd@ucsd.edu',
    gender: 'M',
    language: 'Thai',
    birthday: '1958-06-26',
    cycle: 'night',
  },

  {
    id: 15,
    first_name: 'Cele',
    last_name: 'La Torre',
    email: 'clatorree@cbsnews.com',
    gender: 'F',
    language: 'Papiamento',
    birthday: '1969-08-15',
    cycle: 'morning',
  },

  {
    id: 16,
    first_name: 'Reed',
    last_name: 'Andrich',
    email: 'randrichf@usa.gov',
    gender: 'M',
    language: 'Tswana',
    birthday: '1982-05-16',
    cycle: 'morning',
  },

  {
    id: 17,
    first_name: 'Kathye',
    last_name: 'Tollerfield',
    email: 'ktollerfieldg@cdc.gov',
    gender: 'F',
    language: 'Catalan',
    birthday: '1986-05-05',
    cycle: 'morning',
  },

  {
    id: 18,
    first_name: 'Chaddie',
    last_name: 'Winger',
    email: 'cwingerh@xinhuanet.com',
    gender: 'M',
    language: 'Sotho',
    birthday: '1950-10-10',
    cycle: 'morning',
  },

  {
    id: 19,
    first_name: 'Archibald',
    last_name: 'Barthram',
    email: 'abarthrami@hatena.ne.jp',
    gender: 'M',
    language: 'Moldovan',
    birthday: '1974-02-09',
    cycle: 'morning',
  },

  {
    id: 20,
    first_name: 'Fredericka',
    last_name: 'Lumox',
    email: 'flumoxj@jigsy.com',
    gender: 'F',
    language: 'Dzongkha',
    birthday: '1997-05-05',
    cycle: 'night',
  },
]
